packages:
  - "packages/*"

onlyBuiltDependencies:
  - esbuild
  - unrs-resolver

peerDependencyRules:
  ignoreMissing:
    - typescript
    - svelte
    - eslint-plugin-import
    - eslint
    - prettier

catalog:
  local-pkg: ^1.1.2
  natsort: ^2.0.3

catalogs:
  build:
    "@antfu/ni": "^26.1.0"
    "@types/node": "^24.7.2"
    "@typescript/native-preview": "7.0.0-dev.20250614.1"
    "bumpp": "^10.3.1"
    "execa": "^9.6.0"
    "tsdown": "^0.15.7"
    "tsup": "^8.5.0"
    "tsx": "^4.20.6"
    "typescript": "^5.9.3"
    "vitest": "^3.2.4"
    "eslint-vitest-rule-tester": "^2.2.2"
    "eslint-typegen": "^2.3.0"

  eslint:
    "eslint": "^9.37.0"
    "@typescript-eslint/parser": "^8.46.1"
    "@typescript-eslint/types": "^8.46.1"
    "@typescript-eslint/utils": "^8.46.1"
    "typescript-eslint": "^8.46.1"
    "@eslint-community/eslint-plugin-eslint-comments": "^4.5.0"
    "@html-eslint/eslint-plugin": "^0.47.0"
    "@html-eslint/parser": "^0.47.0"
    "@stylistic/eslint-plugin": "^5.4.0"
    "@unocss/eslint-config": "^66.5.3"
    "@vitest/eslint-plugin": "^1.3.19"
    "eslint-config-flat-gitignore": "^2.1.0"
    "eslint-flat-config-utils": "^2.1.4"
    "eslint-import-resolver-typescript": "^4.4.4"
    "eslint-mdx": "^3.6.2"
    "eslint-plugin-antfu": "^3.1.1"
    "eslint-plugin-array-func": "^5.1.0"
    "eslint-plugin-astro": "^1.3.1"
    "eslint-plugin-case-police": "^2.0.0"
    "eslint-plugin-html": "^8.1.3"
    "eslint-plugin-import-x": "^4.16.1"
    "eslint-plugin-jest-formatting": "^3.1.0"
    "eslint-plugin-jsonc": "^2.21.0"
    "eslint-plugin-mdx": "^3.6.2"
    "eslint-plugin-n": "^17.23.1"
    "eslint-plugin-no-await-in-promise": "^3.0.1"
    "eslint-plugin-no-explicit-type-exports": "^0.12.1"
    "eslint-plugin-no-only-tests": "^3.3.0"
    "eslint-plugin-only-error": "^1.0.2"
    "eslint-plugin-pnpm": "^1.2.0"
    "eslint-plugin-promise": "^7.2.1"
    "eslint-plugin-regexp": "^2.10.0"
    "eslint-plugin-solid": "^0.14.5"
    "eslint-plugin-toml": "^0.12.0"
    "eslint-plugin-unicorn": "^61.0.2"
    "eslint-plugin-unused-imports": "^4.2.0"
    "eslint-plugin-vue": "^10.5.0"
    "eslint-plugin-yml": "^1.19.0"
    "jsonc-eslint-parser": "^2.4.1"
    "toml-eslint-parser": "^0.10.0"
    "astro-eslint-parser": "^1.2.2"
    "vue-eslint-parser": "^10.2.0"
    "yaml-eslint-parser": "^1.3.0"
    "globals": "^16.4.0"

  prettier:
    "prettier": "^3.6.2"
    "prettier-plugin-astro": "^0.14.1"
    "prettier-plugin-pkgsort": "^0.2.1"
    "prettier-plugin-toml": "^2.0.6"

  peers:
    eslint: ^9.37.0
    prettier: ^3.6.2
