module.exports = {
  extends: require.resolve("./base"),
  rules: {
    "vue/multi-word-component-names": "warn",
    "vue/no-arrow-functions-in-watch": "warn",
    "vue/no-async-in-computed-properties": "warn",
    "vue/no-child-content": "warn",
    "vue/no-computed-properties-in-data": "warn",
    "vue/no-custom-modifiers-on-v-model": "warn",
    "vue/no-dupe-keys": "warn",
    "vue/no-dupe-v-else-if": "warn",
    "vue/no-duplicate-attributes": "warn",
    "vue/no-export-in-script-setup": "warn",
    "vue/no-multiple-template-root": "warn",
    "vue/no-mutating-props": "warn",
    "vue/no-parsing-error": "warn",
    "vue/no-ref-as-operand": "warn",
    "vue/no-reserved-component-names": "warn",
    "vue/no-reserved-keys": "warn",
    "vue/no-reserved-props": [
      "warn",
      {
        vueVersion: 2,
      },
    ],
    "vue/no-setup-props-destructure": "warn",
    "vue/no-shared-component-data": "warn",
    "vue/no-side-effects-in-computed-properties": "warn",
    "vue/no-template-key": "warn",
    "vue/no-textarea-mustache": "warn",
    "vue/no-unused-components": "warn",
    "vue/no-unused-vars": "warn",
    "vue/no-use-computed-property-like-method": "warn",
    "vue/no-use-v-if-with-v-for": "warn",
    "vue/no-useless-template-attributes": "warn",
    "vue/no-v-for-template-key": "warn",
    "vue/no-v-model-argument": "warn",
    "vue/no-v-text-v-html-on-component": "warn",
    "vue/require-component-is": "warn",
    "vue/require-prop-type-constructor": "warn",
    "vue/require-render-return": "warn",
    "vue/require-v-for-key": "warn",
    "vue/require-valid-default-prop": "warn",
    "vue/return-in-computed-property": "warn",
    "vue/return-in-emits-validator": "warn",
    "vue/use-v-on-exact": "warn",
    "vue/valid-attribute-name": "warn",
    "vue/valid-define-emits": "warn",
    "vue/valid-define-props": "warn",
    "vue/valid-model-definition": "warn",
    "vue/valid-next-tick": "warn",
    "vue/valid-template-root": "warn",
    "vue/valid-v-bind-sync": "warn",
    "vue/valid-v-bind": "warn",
    "vue/valid-v-cloak": "warn",
    "vue/valid-v-else-if": "warn",
    "vue/valid-v-else": "warn",
    "vue/valid-v-for": "warn",
    "vue/valid-v-html": "warn",
    "vue/valid-v-if": "warn",
    "vue/valid-v-model": "warn",
    "vue/valid-v-on": "warn",
    "vue/valid-v-once": "warn",
    "vue/valid-v-pre": "warn",
    "vue/valid-v-show": "warn",
    "vue/valid-v-slot": "warn",
    "vue/valid-v-text": "warn",
  },
};
